"""
Django settings for config project (FICCTURA + UNIVERSO 404).

Generated by 'django-admin startproject' using Django 6.1, adaptado
siguiendo la misma estructura que el proyecto regalbox (Django + Tailwind + JS).

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables de .env (API keys, etc.) como variables de entorno.
load_dotenv(BASE_DIR / ".env")


# Deploy en Render (18/8): todo lo sensible/ambiental sale de variables
# de entorno — en local las toma del .env (python-dotenv, ver arriba),
# en Render se cargan en el dashboard del servicio. Los defaults de acá
# son SIEMPRE los de desarrollo local, nunca los de producción, para
# que un .env faltante nunca deje el sitio corriendo en modo inseguro
# sin que salte a la vista (DEBUG por default en False sería peor:
# fallarías en local con errores 500 pelados sin darte cuenta de por qué).

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-s_g+i8%tg4&$!kfu(*v9miunv@$7cf6&!%bee6fk&6)*5&8z24',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ".localhost" con el punto adelante = permite cualquier subdominio
# (u404.localhost, ficctura.localhost, etc.), no solo "localhost" pelado.
# En Render: se le suma automáticamente el hostname *.onrender.com que
# Render inyecta solo (RENDER_EXTERNAL_HOSTNAME), y cualquier dominio
# propio que se agregue vía la env var ALLOWED_HOSTS (separados por coma)
# — así, cuando lleguen los dominios reales, alcanza con cargar esa env
# var en el dashboard de Render, sin tocar código de nuevo.
ALLOWED_HOSTS = ['localhost', '.localhost', '127.0.0.1']

_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host:
    ALLOWED_HOSTS.append(_render_host)

_extra_hosts = os.environ.get('ALLOWED_HOSTS', '')
if _extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'catalog',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise: sirve los estáticos compilados (collectstatic) directo
    # desde el proceso de Django, sin depender de un Nginx aparte — es
    # el patrón estándar para un web service simple en Render.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Detecta qué marca (U404 o FICCTURA) corresponde a la request según
    # el host. Debe ir después de Common/Security y antes de cualquier
    # vista que use request.brand. Ver core/middleware.py.
    'core.middleware.BrandMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'core.context_processors.brand',
                'core.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite en local (como siempre). En producción, si existe DATABASE_URL
# se usa esa en su lugar (Postgres de Neon — ver render.yaml, se carga
# a mano como secret en Render porque Neon no es un recurso que Render
# gestione solo): SQLite vive en el disco del propio proceso, que en
# Render es efímero y se borra en cada deploy — nunca sirve para
# guardar pedidos/productos reales ahí.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    DATABASES['default'] = dj_database_url.parse(_database_url, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: comprime (gzip/brotli) los estáticos ya recolectados por
# collectstatic. Se usa la variante SIN manifest (no
# ManifestStaticFilesStorage) a propósito — el proyecto ya tiene su
# propio cache-busting casero (`{% static_v %}`, ver
# core/templatetags/asset_tags.py) y Manifest exige que TODOS los
# archivos referenciados por cualquier {% static %} existan al
# momento del collectstatic o hace fallar el build entero.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'

# OJO (pendiente, no es parte de este arreglo): en Render el disco es
# efímero salvo que se pague un Disk persistente — las fotos que suba
# el panel acá se van a borrar en cada deploy. Sirve para probar el
# sitio ya, pero antes de cargar catálogo real hay que resolver esto
# (Disk persistente de Render, o subir las imágenes a un storage
# externo tipo S3/Cloudinary vía django-storages).
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================================
# Seguridad HTTPS — solo entran en juego con DEBUG=False (producción).
# Render termina el TLS en su propio proxy y reenvía por HTTP interno
# con el header X-Forwarded-Proto; sin SECURE_PROXY_SSL_HEADER, Django
# no se entera de que la conexión original era HTTPS y SECURE_SSL_REDIRECT
# termina en loop infinito de redirects.
# ==========================================================
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 semana para arrancar; se puede subir a 1 año (31536000) una vez confirmado que todo sirve bien por HTTPS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# CSRF_TRUSTED_ORIGINS: Django exige que cada origin que manda POSTs
# (login del panel, checkout, etc.) esté acá explícitamente cuando se
# sirve por HTTPS. Se arma solo con ALLOWED_HOSTS (mismo criterio: el
# hostname de Render se agrega solo, los dominios propios se suman
# después vía env var, sin tocar código).
CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS if host not in ('localhost', '.localhost', '127.0.0.1')]


# ==========================================================
# FICCTURA + UNIVERSO 404 — arquitectura de dos marcas
# ==========================================================
#
# Un solo proyecto Django sirve las dos webs (mismo catálogo/carrito de
# base, según el brief: "compra unificada desde U404"). La marca activa
# se resuelve por dominio en core/middleware.py::BrandMiddleware.
#
# En producción, cada dominio real apunta acá:
#   www.universo404.com.ar -> 'u404'
#   ficctura.com.ar        -> 'ficctura'
#
# En desarrollo local se distinguen por SUBDOMINIO de *.localhost — los
# navegadores modernos resuelven cualquier "algo.localhost" a la propia
# máquina sin tocar el archivo hosts del sistema (RFC 6761), así que un
# solo servidor en un solo puerto sirve las dos marcas, igual que en
# producción real (por dominio, no por puerto). Un solo comando
# "manage.py runserver 8020" y accedés a las dos:
#   http://u404.localhost:8020/
#   http://ficctura.localhost:8020/
# Se dejan también los viejos localhost:8010/8011 por compatibilidad,
# no molestan.
BRAND_HOSTS = {
    'www.universo404.com.ar': 'u404',
    'universo404.com.ar': 'u404',
    'u404.localhost:8020': 'u404',
    'localhost:8010': 'u404',
    '127.0.0.1:8010': 'u404',

    'ficctura.com.ar': 'ficctura',
    'www.ficctura.com.ar': 'ficctura',
    'ficctura.localhost:8020': 'ficctura',
    'localhost:8011': 'ficctura',
    '127.0.0.1:8011': 'ficctura',
}

# Marca por defecto cuando el host no matchea nada de arriba (ej. correr
# "manage.py runserver" sin puerto explícito, o healthchecks).
DEFAULT_BRAND = 'u404'

# Nombre para mostrar y WhatsApp de contacto por marca. Los números son
# placeholder — reemplazar cuando el cliente confirme el número de la
# marca (el brief menciona la intención de comprar un número separado,
# pero no lo confirma).
BRANDS = {
    'u404': {
        'name': 'UNIVERSO 404',
        'whatsapp_number': '5491155698878',  # 11 5569-8878 — coordinación de transferencia/efectivo (13/8)
        # Confirmado en el informe de onboarding: se terminó usando este
        # usuario tras problemas con universo.404/uniforme.404.
        'instagram': 'eluniverso404',
    },
    'ficctura': {
        'name': 'FICCTURA',
        'whatsapp_number': '5491155698878',  # 11 5569-8878 — coordinación de transferencia/efectivo (13/8)
        'instagram': 'ficctura',  # instagram.com/ficctura (13/8)
    },
}

# URL absoluta a la tienda de cada marca, para el gateway split-screen
# (home.html) que enlaza de una marca a la otra — a veces cruzando de
# dominio. En dev se arma con los subdominios de *.localhost; en
# producción, con los dominios reales.
if DEBUG:
    BRAND_URLS = {
        'u404': 'http://u404.localhost:8020/tienda/',
        'ficctura': 'http://ficctura.localhost:8020/tienda/',
    }
else:
    BRAND_URLS = {
        'u404': 'https://www.universo404.com.ar/tienda/',
        'ficctura': 'https://ficctura.com.ar/tienda/',
    }


# ==========================================================
# PAYWAY (cobro con tarjeta) — motor Decidir
# ==========================================================
# Payway Argentina corre sobre el motor Decidir (confirmado contra sus
# SDKs públicos: github.com/decidir/sdk-javascript-v2,
# github.com/decidir/sdk-nodejs-v2). Las claves REALES las entrega
# Payway (soporte@payway.com.ar) recién cuando el cliente activa
# CUIT/facturación — ver brief/preguntas-pendientes-cliente.md. Vacías
# = el checkout deshabilita "tarjeta" con una nota, en vez de fingir
# que cobra y romper.
PAYWAY_PUBLIC_KEY = os.environ.get('PAYWAY_PUBLIC_KEY', '')
PAYWAY_PRIVATE_KEY = os.environ.get('PAYWAY_PRIVATE_KEY', '')
PAYWAY_ENV = os.environ.get('PAYWAY_ENV', 'developer')  # 'developer' (sandbox) o 'production'

PAYWAY_API_BASE_URL = (
    'https://live.decidir.com/api/v2' if PAYWAY_ENV == 'production'
    else 'https://developers.decidir.com/api/v2'
)

# SDK de tokenización del lado del cliente (nunca toca la private key).
PAYWAY_JS_SDK_URL = 'https://ventasonline.payway.com.ar/static/v2.6.4/decidir.js'


# ==========================================================
# WHATSAPP DE CONFIRMACIÓN (Twilio) — ver catalog/whatsapp.py
# ==========================================================
# Manda un WhatsApp automático al cliente con los datos de su compra.
# Hace falta una cuenta de Twilio + un número de WhatsApp Business
# aprobado — ninguno existe todavía (ni siquiera hay un WhatsApp
# cargado en BRANDS más arriba). Vacío = no se manda nada, el checkout
# sigue funcionando igual que ahora (ver nota en catalog/views.py).
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_WHATSAPP_FROM = os.environ.get('TWILIO_WHATSAPP_FROM', '')  # ej. '+14155238886' (sandbox) o el número Business real, con código de país
