# Generated by Django 6.1 on 2026-08-10 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('u404', 'UNIVERSO 404'), ('ficctura', 'FICCTURA')], max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=70)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_coming_soon', models.BooleanField(default=False, help_text="Se muestra como 'Próximamente' sin productos reales, con botón de interés.")),
            ],
            options={
                'verbose_name_plural': 'categorías',
                'ordering': ['brand', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('u404', 'UNIVERSO 404'), ('ficctura', 'FICCTURA')], max_length=10)),
                ('name', models.CharField(help_text='Ej: "Sobrio", "Primera Chamba"', max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='Copy/historia del producto. Si el brief ya trae el texto para este modelo, pegarlo tal cual — no reescribir.')),
                ('material', models.CharField(blank=True, help_text='Ej: "Algodón peinado 20/1"', max_length=120)),
                ('fit_notes', models.TextField(blank=True, help_text='Notas de calce (ej: "deja espacio en el abdomen, no aprieta la panza").')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('sold_out', 'Agotado')], default='available', max_length=10)),
                ('is_limited_edition', models.BooleanField(default=False, help_text='Diseños con licencia real (bandas, franquicias) van como "edición limitada" — ver brief 7/8.')),
                ('license_status', models.CharField(choices=[('not_needed', 'No requiere licencia'), ('pending', 'Licencia pendiente de resolver'), ('cleared', 'Licencia resuelta')], default='not_needed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productos/')),
                ('alt_text', models.CharField(blank=True, max_length=140)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='Blanco', max_length=30)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=40)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.size')),
            ],
            options={
                'ordering': ['size__order', 'color'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
        migrations.CreateModel(
            name='SizeMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='pecho (cm)')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='largo (cm)')),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Medida a la altura del ombligo — pedida explícitamente en el brief.', max_digits=5, null=True, verbose_name='ombligo/abdomen (cm)')),
                ('sleeve_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='manga (cm)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='catalog.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.size')),
            ],
            options={
                'ordering': ['size__order'],
                'unique_together': {('product', 'size')},
            },
        ),
    ]
