# Generated by Django 6.1 on 2026-08-10 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='urgency_countdown_ends_at',
            field=models.DateTimeField(blank=True, help_text='Para "reiniciar" la cuenta regresiva simplemente cambiá esta fecha.', null=True, verbose_name='La promo termina el'),
        ),
        migrations.AddField(
            model_name='product',
            name='urgency_stock_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total del lote (ej: 100)'),
        ),
        migrations.AddField(
            model_name='product',
            name='urgency_stock_remaining',
            field=models.PositiveIntegerField(blank=True, help_text='Se actualiza a mano — no está atado al stock real de las variantes.', null=True, verbose_name='Unidades restantes del lote (ej: 6)'),
        ),
        migrations.AddField(
            model_name='product',
            name='urgency_type',
            field=models.CharField(choices=[('none', 'Ninguno'), ('stock', 'Contador de stock (ej: "6 / 100 unidades")'), ('countdown', 'Cuenta regresiva a una fecha límite'), ('both', 'Los dos')], default='none', max_length=10, verbose_name='Widget de urgencia'),
        ),
        migrations.CreateModel(
            name='ProductReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('contact', models.CharField(help_text='Teléfono o email', max_length=100, verbose_name='contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.size', verbose_name='talle deseado')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
