# Generated by Django 6.1 on 2026-08-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_urgency_countdown_ends_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('u404', 'UNIVERSO 404'), ('ficctura', 'FICCTURA')], max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, help_text='Ej: "¡Preventa exclusiva!" — texto del banner, aparte del contador.', max_length=140)),
                ('link_url', models.CharField(blank=True, help_text='A dónde lleva el banner al clickear (opcional). Ej: /catalogo/', max_length=200)),
                ('urgency_type', models.CharField(choices=[('none', 'Ninguno'), ('stock', 'Contador de stock (ej: "6 / 100 unidades")'), ('countdown', 'Cuenta regresiva a una fecha límite'), ('both', 'Los dos')], default='none', max_length=10)),
                ('urgency_stock_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total del lote (ej: 100)')),
                ('urgency_stock_remaining', models.PositiveIntegerField(blank=True, help_text='Se actualiza a mano. Para "reiniciar", cambiá este número.', null=True, verbose_name='Unidades restantes (ej: 6)')),
                ('urgency_countdown_ends_at', models.DateTimeField(blank=True, help_text='Para "reiniciar" la cuenta regresiva, cambiá esta fecha.', null=True, verbose_name='Termina el')),
            ],
            options={
                'verbose_name': 'promoción de marca',
                'verbose_name_plural': 'promociones de marca',
            },
        ),
    ]
