# Generated by Django 6.1 on 2026-08-11 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_brandpromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('u404', 'UNIVERSO 404'), ('ficctura', 'FICCTURA')], max_length=10)),
                ('name', models.CharField(help_text='Ej: "3x2 en remeras", "Buzo + remera de regalo"', max_length=100)),
                ('badge_text', models.CharField(blank=True, help_text='Texto corto para el catálogo, ej: "3X2" o "2X1 REGALO". Si queda vacío, no se muestra badge.', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('buy_quantity', models.PositiveIntegerField(default=3, verbose_name='cuántas unidades')),
                ('get_quantity', models.PositiveIntegerField(default=1, verbose_name='cuántas unidades de regalo/descuento')),
                ('get_discount_percent', models.PositiveIntegerField(default=100, help_text='100 = gratis. Ej: 50 = mitad de precio.', verbose_name='% de descuento en esas unidades')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='empieza el')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='termina el')),
                ('buy_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_as_buy', to='catalog.category', verbose_name='comprando de la categoría')),
                ('get_category', models.ForeignKey(blank=True, help_text='Vacío = la misma categoría que "comprando de" (para un 3x2 clásico).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_as_get', to='catalog.category', verbose_name='te regala/descuenta de la categoría')),
            ],
            options={
                'verbose_name': 'promoción (llevá X, llevate Y)',
                'verbose_name_plural': 'promociones (llevá X, llevate Y)',
                'ordering': ['-id'],
            },
        ),
    ]
