# Generated by Django 6.1 on 2026-08-11 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandpromotion',
            name='linked_promotion',
            field=models.ForeignKey(blank=True, help_text='Si el banner anuncia una promo puntual (3x2, etc.), vinculala acá — el banner se apaga solo cuando esta promoción se desactiva. Si la vinculás, dejá "mensaje" vacío: se arma solo a partir de la promo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.promotion'),
        ),
        migrations.AlterField(
            model_name='brandpromotion',
            name='message',
            field=models.CharField(blank=True, help_text='Ej: "¡Preventa exclusiva!" — texto del banner. Se ignora si hay una promoción vinculada arriba.', max_length=140),
        ),
    ]
