# Generated by Django 6.1 on 2026-08-11 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_brandpromotion_linked_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('u404', 'UNIVERSO 404'), ('ficctura', 'FICCTURA')], max_length=10)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('contact', models.CharField(help_text='WhatsApp o email', max_length=100, verbose_name='contacto')),
                ('address', models.CharField(blank=True, help_text='Solo hace falta si el método de entrega es correo o mensajería.', max_length=255, verbose_name='dirección')),
                ('delivery_method', models.CharField(choices=[('correo', 'Correo'), ('retiro', 'Retiro en persona'), ('mensajeria', 'Mensajería')], max_length=12)),
                ('payment_preference', models.CharField(choices=[('tarjeta', 'Tarjeta (3 cuotas)'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], max_length=14)),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de contacto'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.order')),
            ],
        ),
    ]
