# Generated by Django 6.1 on 2026-08-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['order', 'name'], 'verbose_name': 'talle', 'verbose_name_plural': 'talles'},
        ),
    ]
