# Generated by Django 6.1 on 2026-08-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_options_alter_size_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandpromotion',
            name='brand',
            field=models.CharField(choices=[('u404', 'UNIVERSO 404'), ('ficctura', 'FICCTURA')], max_length=10, unique=True, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='brandpromotion',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='brandpromotion',
            name='link_url',
            field=models.CharField(blank=True, help_text='A dónde lleva el banner al clickear (opcional). Ej: /catalogo/', max_length=200, verbose_name='link del banner'),
        ),
        migrations.AlterField(
            model_name='brandpromotion',
            name='linked_promotion',
            field=models.ForeignKey(blank=True, help_text='Si el banner anuncia una promo puntual (3x2, etc.), vinculala acá — el banner se apaga solo cuando esta promoción se desactiva. Si la vinculás, dejá "mensaje" vacío: se arma solo a partir de la promo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.promotion', verbose_name='promoción vinculada'),
        ),
        migrations.AlterField(
            model_name='brandpromotion',
            name='message',
            field=models.CharField(blank=True, help_text='Ej: "¡Preventa exclusiva!" — texto del banner. Se ignora si hay una promoción vinculada arriba.', max_length=140, verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='category',
            name='brand',
            field=models.CharField(choices=[('u404', 'UNIVERSO 404'), ('ficctura', 'FICCTURA')], max_length=10, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='brand',
            field=models.CharField(choices=[('u404', 'UNIVERSO 404'), ('ficctura', 'FICCTURA')], max_length=10, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de contacto'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=10, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('u404', 'UNIVERSO 404'), ('ficctura', 'FICCTURA')], max_length=10, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Ej: "Sobrio", "Primera Chamba"', max_length=80, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('sold_out', 'Agotado')], default='available', max_length=10, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Texto corto para el catálogo, ej: "3X2" o "2X1 REGALO". Si queda vacío, no se muestra badge.', max_length=20, verbose_name='texto del badge'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='brand',
            field=models.CharField(choices=[('u404', 'UNIVERSO 404'), ('ficctura', 'FICCTURA')], max_length=10, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(help_text='Ej: "3x2 en remeras", "Buzo + remera de regalo"', max_length=100, verbose_name='nombre'),
        ),
    ]
