# Generated by Django 6.1 on 2026-08-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_brandpromotion_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandpromotion',
            name='urgency_type',
            field=models.CharField(choices=[('none', 'Ninguno'), ('stock', 'Contador de stock (ej: "6 / 100 unidades")'), ('countdown', 'Cuenta regresiva a una fecha límite'), ('both', 'Los dos')], default='none', max_length=10, verbose_name='widget de urgencia'),
        ),
    ]
