# Generated by Django 6.1 on 2026-08-12 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_brandpromotion_urgency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_coming_soon',
            field=models.BooleanField(default=False, help_text="Se muestra como 'Próximamente' sin productos reales, con botón de interés.", verbose_name='próximamente'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('correo', 'Correo'), ('retiro', 'Retiro en persona'), ('mensajeria', 'Mensajería')], max_length=12, verbose_name='método de entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='descuento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_preference',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta (3 cuotas)'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], max_length=14, verbose_name='forma de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_limited_edition',
            field=models.BooleanField(default=False, help_text='Diseños con licencia real (bandas, franquicias) van como "edición limitada" — ver brief 7/8.', verbose_name='edición limitada'),
        ),
        migrations.AlterField(
            model_name='product',
            name='license_status',
            field=models.CharField(choices=[('not_needed', 'No requiere licencia'), ('pending', 'Licencia pendiente de resolver'), ('cleared', 'Licencia resuelta')], default='not_needed', max_length=12, verbose_name='estado de la licencia'),
        ),
    ]
