# Generated by Django 6.1 on 2026-08-12 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_category_is_coming_soon_alter_category_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['brand', 'order', 'name'], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterField(
            model_name='productreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada'),
        ),
        migrations.AlterField(
            model_name='productreservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.product', verbose_name='producto'),
        ),
    ]
