# Generated by Django 6.1 on 2026-08-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('u404', 'UNIVERSO 404'), ('ficctura', 'FICCTURA')], max_length=10, unique=True, verbose_name='marca')),
                ('is_active', models.BooleanField(default=False, verbose_name='activo')),
                ('transferencia_percent', models.PositiveIntegerField(default=0, help_text='Ej: 10 = 10% off pagando por transferencia. 0 = sin descuento.', verbose_name='descuento por transferencia (%)')),
                ('efectivo_percent', models.PositiveIntegerField(default=0, help_text='Ej: 10 = 10% off pagando en efectivo. 0 = sin descuento.', verbose_name='descuento por efectivo (%)')),
            ],
            options={
                'verbose_name': 'descuento por forma de pago',
                'verbose_name_plural': 'descuentos por forma de pago',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='descuento por forma de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento por "llevá X, llevate Y". El de transferencia/efectivo está aparte, abajo.', max_digits=10, verbose_name='descuento por promo'),
        ),
    ]
