# Generated by Django 6.1 on 2026-08-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_orderitem_options_alter_orderitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdiscount',
            name='banner_text',
            field=models.CharField(blank=True, help_text='Lo que se lee en el banner de arriba de la tienda mientras esté activo. Ej: "10% OFF PAGANDO POR TRANSFERENCIA". Si lo dejás vacío, se arma solo a partir de los % cargados arriba.', max_length=100, verbose_name='texto del banner'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='banner_text',
            field=models.CharField(blank=True, help_text='Lo que se lee en el banner de arriba de la tienda mientras esté activa. Ej: "3X2 EN REMERAS BÁSICAS". Si lo dejás vacío, se arma solo con el texto del badge (o el nombre, si no hay badge).', max_length=100, verbose_name='texto del banner'),
        ),
    ]
