# Generated by Django 6.1 on 2026-08-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_paymentdiscount_banner_text_promotion_banner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdiscount',
            name='countdown_ends_at',
            field=models.DateTimeField(blank=True, help_text='Opcional: si lo cargás, en el banner aparece "Termina en HH:MM:SS" al lado del texto de este descuento. Dejalo vacío para que el descuento se vea sin contador. Para "reiniciar" la cuenta regresiva, simplemente cambiá esta fecha.', null=True, verbose_name='cuenta regresiva — termina el'),
        ),
    ]
