# Generated by Django 6.1 on 2026-08-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_paymentdiscount_countdown_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(help_text='WhatsApp (con código de país)', max_length=100, verbose_name='contacto'),
        ),
        migrations.AlterField(
            model_name='productreservation',
            name='contact',
            field=models.CharField(help_text='WhatsApp (con código de país)', max_length=100, verbose_name='contacto'),
        ),
    ]
