# Generated by Django 6.1 on 2026-08-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_order_contact_alter_productreservation_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, help_text='Opcional — si esta foto es de un color puntual (tiene que coincidir con el texto del color de la variante, ej. "Negro"). Vacío = foto general.', max_length=30, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='hex_color',
            field=models.CharField(blank=True, help_text='Opcional — para mostrar un círculo con el color real. Ej: #1a1a1a', max_length=7, verbose_name='color (hex)'),
        ),
    ]
