# Generated by Django 6.1 on 2026-08-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_seed_size_xxl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: "Junior", "CEO"', max_length=40, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tagline', models.CharField(help_text='Ej: "Vas bien pero recién estás arrancando"', max_length=140, verbose_name='bajada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('ficctura_negro_qty', models.PositiveIntegerField(default=0, verbose_name='unidades Sobrio Negro')),
                ('ficctura_blanco_qty', models.PositiveIntegerField(default=0, verbose_name='unidades Sobrio Blanco')),
                ('u404_qty', models.PositiveIntegerField(default=0, help_text='El cliente elige qué modelo de U404 quiere para cada una.', verbose_name='unidades U404')),
                ('bonus_basica_qty', models.PositiveIntegerField(default=0, help_text='Unidades EXTRA de Sobrio (Ficctura) totalmente gratis — ej: CEO = 1. El cliente elige color y talle igual.', verbose_name='básicas de regalo')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='% de descuento')),
                ('free_shipping', models.BooleanField(default=True, verbose_name='envío gratis')),
            ],
            options={
                'verbose_name': 'pack',
                'verbose_name_plural': 'packs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
