# Generated by Django 6.1 on 2026-09-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_rename_pack_junior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('sold_out', 'Reserva')], default='available', max_length=10, verbose_name='estado'),
        ),
    ]
