# Generated by Django 6.1 on 2026-09-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_rename_pack_junior_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Si cargás productos acá, la promo cuenta SOLO entre ellos — para un 2x1/3x2 puntual entre unos pocos diseños, no toda la categoría. Vacío = se comporta como siempre, por categoría entera.', related_name='promotions', to='catalog.product', verbose_name='solo estos productos (opcional)'),
        ),
    ]
